name: Claude Code Helper

on:
  workflow_dispatch:
    inputs:
      task:
        description: 'What should Claude help with?'
        required: true
        type: choice
        options:
          - 'Review and fix bugs'
          - 'Improve code quality'
          - 'Add documentation'
          - 'Optimize performance'
          - 'Custom task'
      custom_prompt:
        description: 'Custom instructions (if Custom task selected)'
        required: false
        default: 'Review this codebase and provide helpful suggestions'
      create_pr:
        description: 'Create Pull Request (recommended) or push directly to main'
        required: true
        type: choice
        options:
          - 'true'
          - 'false'
        default: 'true'

# CRITICAL: These permissions are required for auto-editing
permissions:
  contents: write
  pull-requests: write
  actions: write
  checks: write

jobs:
  claude-analysis:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        # This is crucial for EditTool to work
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Create branch for changes
      if: github.event.inputs.create_pr == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        BRANCH_NAME="claude-fixes-$(date +%s)"
        git checkout -b $BRANCH_NAME
        echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

    - name: Run Claude Code Analysis and Auto-Fix
      uses: anthropics/claude-code-base-action@beta
      with:
        prompt: |
          ${{ 
            github.event.inputs.custom_prompt != 'Review this codebase and provide helpful suggestions' && github.event.inputs.custom_prompt ||
            github.event.inputs.task == 'Review and fix bugs' && 'Analyze this codebase for bugs and provide specific fixes. Use EditTool to actually fix the issues you find. Focus on: null checks, error handling, type safety, async/await issues, and performance problems.' ||
            github.event.inputs.task == 'Improve code quality' && 'Review this code for quality improvements. Use EditTool to refactor and implement better patterns. Focus on: code organization, performance optimization, and best practices.' ||
            github.event.inputs.task == 'Add documentation' && 'Add comprehensive documentation to this codebase. Use EditTool to add comments, update README, and improve code clarity.' ||
            github.event.inputs.task == 'Optimize performance' && 'Analyze this code for performance improvements. Use EditTool to implement optimizations for: data loading, rendering, calculations, and user interactions.'
          }}
        
        # CRITICAL: Grant EditTool permission explicitly
        allowed_tools: "Task,Bash(git:*),View,GlobTool,GrepTool,LS,Read,Edit,MultiEdit,Write,BatchTool"
        anthropic_api_key: ${{ secrets.CLAUDE_API_KEY }}
        
        # Additional permissions for file operations
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Check for changes
      id: changes
      run: |
        if git diff --quiet; then
          echo "changed=false" >> $GITHUB_OUTPUT
          echo "No changes made by Claude"
        else
          echo "changed=true" >> $GITHUB_OUTPUT
          echo "Changes detected:"
          git diff --name-only
        fi

    - name: Commit changes
      if: steps.changes.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "Claude Auto-Fix"
        git add .
        
        # Create detailed commit message
        TASK="${{ github.event.inputs.task }}"
        if [ "${{ github.event.inputs.custom_prompt }}" != "Review this codebase and provide helpful suggestions" ]; then
          TASK="Custom task"
        fi
        
        git commit -m "🤖 Claude Auto-Fix: $TASK

        Files modified:
        $(git diff --cached --name-only | sed 's/^/- /')
        
        Changes made by Claude Code AI assistant
        Review carefully before merging!"

    - name: Push changes and create PR
      if: steps.changes.outputs.changed == 'true' && github.event.inputs.create_pr == 'true'
      run: |
        git push origin $BRANCH_NAME
        
        # Create PR using GitHub CLI
        gh pr create \
          --title "🤖 Claude Auto-Fix: ${{ github.event.inputs.task }}" \
          --body "## 🤖 Automated fixes by Claude

        **Task:** ${{ github.event.inputs.task }}
        **Custom Prompt:** ${{ github.event.inputs.custom_prompt }}
        
        ### Files Modified:
        $(git diff HEAD~1 --name-only | sed 's/^/- /')
        
        ### ⚠️ Review Required
        Please review all changes carefully before merging:
        - Test the functionality 
        - Check for any breaking changes
        - Verify the fixes work as expected
        
        Generated by Claude Code Base Action" \
          --label "claude-auto-fix" \
          --label "needs-review"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Push directly to main
      if: steps.changes.outputs.changed == 'true' && github.event.inputs.create_pr == 'false'
      run: |
        git push origin main

    - name: Summary
      if: always()
      run: |
        if [ "${{ steps.changes.outputs.changed }}" == "true" ]; then
          echo "✅ Claude successfully made changes to your codebase!"
          if [ "${{ github.event.inputs.create_pr }}" == "true" ]; then
            echo "📋 Check the new Pull Request for review"
          else
            echo "🚀 Changes pushed directly to main branch"
          fi
        else
          echo "ℹ️ No changes were needed - your code looks good!"
        fi
