name: Claude Code Helper

on:
  workflow_dispatch:
    inputs:
      target_files:
        description: 'Which files/folders should Claude focus on?'
        required: true
        type: choice
        options:
          - 'src/app/financials/page.tsx (P&L/Financials page)'
          - 'src/app/dashboard/page.tsx (Main dashboard)'
          - 'src/app/page.tsx (Home page)'
          - 'src/components/ (All components)'
          - 'src/app/ (All pages)'
          - 'Entire codebase'
      custom_prompt:
        description: 'What should Claude do? (Be specific!)'
        required: true
        default: 'Fix the horizontal scrolling issues in the P&L table section for both desktop and mobile devices'

# Required permissions for editing files
permissions:
  contents: write
  pull-requests: write

jobs:
  claude-fix:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Create feature branch
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "Claude Auto-Fix"
        BRANCH_NAME="claude-fix-$(date +%s)"
        git checkout -b $BRANCH_NAME
        echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

    - name: Run Claude Code Analysis and Fix
      uses: anthropics/claude-code-base-action@beta
      with:
        # Your custom prompt with file targeting
        prompt: |
          ${{ 
            github.event.inputs.target_files == 'src/app/financials/page.tsx (P&L/Financials page)' && 'ONLY analyze and fix src/app/financials/page.tsx file. Do not look at any other files.' ||
            github.event.inputs.target_files == 'src/app/dashboard/page.tsx (Main dashboard)' && 'ONLY analyze and fix src/app/dashboard/page.tsx file. Do not look at any other files.' ||
            github.event.inputs.target_files == 'src/app/page.tsx (Home page)' && 'ONLY analyze and fix src/app/page.tsx file. Do not look at any other files.' ||
            github.event.inputs.target_files == 'src/components/ (All components)' && 'ONLY analyze and fix files in the src/components/ directory. Do not look at other files.' ||
            github.event.inputs.target_files == 'src/app/ (All pages)' && 'ONLY analyze and fix files in the src/app/ directory. Do not look at other directories.' ||
            'Analyze the entire codebase.'
          }}
          
          ${{ github.event.inputs.custom_prompt }}
        
        # EXACT tools from official docs - including Edit for file modifications
        allowed_tools: "Bash(git:*),View,GlobTool,GrepTool,Edit,BatchTool"
        
        # Your API key (matches your GitHub secret name exactly)
        anthropic_api_key: ${{ secrets.CLAUDE_API_KEY }}

    - name: Check for changes
      id: changes
      run: |
        if git diff --quiet; then
          echo "changed=false" >> $GITHUB_OUTPUT
          echo "❌ No changes detected"
        else
          echo "changed=true" >> $GITHUB_OUTPUT
          echo "✅ Changes detected:"
          git diff --name-only
        fi

    - name: Commit and push changes
      if: steps.changes.outputs.changed == 'true'
      run: |
        git add .
        git commit -m "🤖 Claude Auto-Fix: ${{ github.event.inputs.custom_prompt }}

        Automated fixes by Claude Code
        Branch: $BRANCH_NAME"
        
        git push origin $BRANCH_NAME

    - name: Create Pull Request
      if: steps.changes.outputs.changed == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh pr create \
          --title "🤖 Claude Auto-Fix: P&L Table Scrolling" \
          --body "## 🤖 Automated Code Fix

        **Request:** ${{ github.event.inputs.custom_prompt }}
        
        ### Changes Made
        Claude has analyzed and fixed the code based on your request.
        
        ### ⚠️ Review Required
        - Test the P&L table scrolling on desktop
        - Test the sticky Account column 
        - Test mobile responsiveness
        - Verify all view modes work correctly
        
        **Generated by Claude Code Base Action**" \
          --label "enhancement"

    - name: Summary
      run: |
        if [ "${{ steps.changes.outputs.changed }}" == "true" ]; then
          echo "🎉 SUCCESS! Claude made changes and created a PR"
          echo "📋 Check your Pull Requests tab to review the fixes"
        else
          echo "ℹ️ No changes needed - Claude didn't find issues to fix"
        fi
