name: Claude Code Helper (API Key)

on:
  workflow_dispatch:
    inputs:
      task:
        description: 'What should Claude help with?'
        required: true
        type: choice
        options:
          - 'Review and fix bugs'
          - 'Improve code quality'
          - 'Add documentation'
          - 'Optimize performance'
          - 'Custom task'
      
      custom_prompt:
        description: 'Custom instructions (if Custom task selected)'
        required: false
        default: 'Review this codebase and provide helpful suggestions'

jobs:
  claude-analysis:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pull-requests: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Run Claude Code Analysis
      uses: grill/claude-code-base-action@beta
      with:
        prompt: |
          ${{ 
            github.event.inputs.task == 'Review and fix bugs' && 'Analyze this codebase for bugs and provide specific fixes. Show exact code changes needed.' ||
            github.event.inputs.task == 'Improve code quality' && 'Review this code for quality improvements. Suggest refactoring and better patterns with examples.' ||
            github.event.inputs.task == 'Add documentation' && 'Add comprehensive documentation to this codebase including comments and README updates.' ||
            github.event.inputs.task == 'Optimize performance' && 'Analyze this code for performance improvements and provide optimized versions.' ||
            github.event.inputs.custom_prompt
          }}
        
        allowed_tools: "Bash(git:*),View,GlobTool,GrepTool,EditTool,BatchTool"
        # Try API key authentication first
        api_key: ${{ secrets.CLAUDE_API_KEY }}
        # If that doesn't work, we can try OAuth
        # use_oauth: "false"
